import type { Signal, Fill } from '../types/strategy.js';
import type { MarketCache } from '../data/market-cache.js';

/**
 * Abstract base class for all trading strategies.
 * Each concrete strategy implements detect() to emit signals.
 */
export abstract class BaseStrategy {
  abstract readonly name: string;

  /**
   * Given the latest market cache, detect trading opportunities.
   * Returns an array of 0 or more signals.
   */
  abstract detect(cache: MarketCache): Signal[];

  /**
   * Called when a signal generated by this strategy results in a fill (trade).
   */
  abstract onFill(fill: Fill): void;

  /**
   * Called when a market resolves (settles).
   */
  abstract onResolution(marketId: string, winner: string): void;
}